name: Makefile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Makefile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Make Certs
      run: make certs

    - name: Make Build
      run: make build

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
